############################################################
# +------------------------------------------------------+ #
# |                       Config                         | #
# +------------------------------------------------------+ #
############################################################

# Additional messages used for debugging.
debug: false

# Webhook URL from your Discord server.
webhook-url: ''

# Bot picture for events.
server-icon-url: '' # You must provide one for yourself.
server-username: 'Server'

# Replacement for the /say command. /server
console-icon-url: 'https://haven.netherrain.net/media/images/console-icon.png'
console-username: 'Console'

# Player name formatting.
# Supports PlaceholderAPI if installed.
# DCM Placeholder: %player% - Player's username.
player-username: '%player%'

############################################################
# +------------------------------------------------------+ #
# |                       Events                         | #
# +------------------------------------------------------+ #
############################################################

server-start: true
server-stop: true
join: true
quit: true
death: true
join-quit-player-count: true